services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: surya
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: essentask_db
        ports:
            - 5432:5432